apiVersion: apps/v1
kind: Deployment
metadata:
  name: &instance referral-prescription-web-components
  annotations:
    app.openshift.io/vcs-uri: 'https://git.vascloud.be/nihdi/uhmep/healix/web-components'
    app.openshift.io/connects-to: '["referral-prescription-web-bridge"]'
  labels: &labels
    app.kubernetes.io/part-of: referral-prescription
    app.kubernetes.io/name: referral-prescription-web-components
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: deploywh
    app.openshift.io/runtime: angularjs
    # please verify package.json
    app.openshift.io/runtime-version: 19.2.2
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: *instance
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - env:
            - name: ENV
              value: tst
          image: vas-docker-snapshot.repo.gcloud.belgium.be/nihdi-uhmep-healix-web-components:snapshot
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 20
          name: angular
          ports:
            - containerPort: 8080
              name: http-tcp-8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/spring/logs
              name: shared-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: shared-log
          emptyDir: { }
